AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'asedemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment-whs'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'replace me in repo secrets'
CICD_AGENT_TYPE: 'github'
