AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'ase'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'replace me in repo secrets'
CICD_AGENT_TYPE: 'azuredevops'