AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'asedemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-secure-baseline'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'replace me in repo secrets'
CICD_AGENT_TYPE: 'azuredevops'
CREATE_REDIS_RESOURCE: false
REDIS_TIER: 'Enterprise_E10'