name: 'AzureBicepDeploy'

on:
  workflow_dispatch:

  push:
    branches:
    - main
    paths:
      - 'reference-implementations/LOB-ILB-ASEv3/bicep/**'

  pull_request:
    branches:
    - main
    paths:
      - 'reference-implementations/LOB-ILB-ASEv3/bicep/**'

jobs:
  validate_bicep:
    name: "Validate Bicep files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Validate that bicep builds
        run: az bicep build -f main.bicep
        working-directory: ./reference-implementations/LOB-ILB-ASEv3/bicep

  build-and-deploy:
    name: "Deploy Bicep templates"
    needs: validate_bicep
    runs-on: ubuntu-latest
    steps:

        # Checkout code
      - name: Checkout the code
        uses: actions/checkout@main

      - name: Variable substitution
        uses: microsoft/variable-substitution@v1
        with:
          files:  ./reference-implementations/LOB-ILB-ASEv3/bicep/config.yml
        env:
          ACCOUNT_NAME: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Install yq to parse yaml file
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.5.0/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Parse config.yaml as output to GitHub Actions matrix
        run: |
          echo "config=$(yq e ./reference-implementations/LOB-ILB-ASEv3/bicep/config.yml -j -I=0)" >> $GITHUB_ENV

      - name: Write deployment information to log
        run: |
          echo "Deploying to ${{ fromJson(env.config).AZURE_LOCATION }} with name prefix ${{ fromJson(env.config).RESOURCE_NAME_PREFIX }}"
        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Preflight Validation
        working-directory: ./reference-implementations/LOB-ILB-ASEv3/bicep
        run: |
            az deployment sub validate \
              --location ${{ fromJson(env.config).AZURE_LOCATION }} \
              --parameters workloadName=${{ fromJson(env.config).RESOURCE_NAME_PREFIX }} environment=${{ fromJson(env.config).ENVIRONMENT_TAG }} \
              vmUsername=${{ fromJson(env.config).VM_USERNAME }} vmPassword=${{ secrets.VM_PW }}  location=${{ fromJson(env.config).AZURE_LOCATION }}\
              accountName=${{ secrets.ACCOUNT_NAME }} personalAccessToken=${{ secrets.PAT }} CICDAgentType=${{ fromJson(env.config).CICD_AGENT_TYPE}} \
              --template-file main.bicep

        # Deploy Bicep file, need to point parameters to the main.parameters.json location
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ fromJson(env.config).AZURE_LOCATION }}
          deploymentName:  ${{ fromJson(env.config).DEPLOYMENT_NAME }}
          template: ./reference-implementations/LOB-ILB-ASEv3/bicep/main.bicep
          parameters: >
            workloadName=${{ fromJson(env.config).RESOURCE_NAME_PREFIX }} environment=${{ fromJson(env.config).ENVIRONMENT_TAG }}
            vmUsername=${{ fromJson(env.config).VM_USERNAME }} vmPassword=${{ secrets.VM_PW }} location=${{ fromJson(env.config).AZURE_LOCATION }} 
            accountName=${{ secrets.ACCOUNT_NAME  }} personalAccessToken=${{ secrets.PAT }} CICDAgentType=${{ fromJson(env.config).CICD_AGENT_TYPE}}
  Generate-ARM:
    name: "Generate ARM Template"
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      # Exporting ARM template from the bicep file
      - name: Export ARM template
        working-directory: ./reference-implementations/LOB-ILB-ASEv3/bicep
        run : |
          pwd
          az bicep build --file main.bicep --outfile ../azure-resource-manager/ase-arm.json
          ls -al
      # Uploading exported ARM template to GitHub's artifact 
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: ase-arm
          path: /reference-implementations/LOB-ILB-ASEv3/azure-resource-manager/ase-arm.json
          retention-days: 2

      # Committing and pushing exported ARM template to the same repo.
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: APIM-Action
          author_email: cenkc@microsoft.com
          message: 'ARM template updated'
          cwd: '/reference-implementations/LOB-ILB-ASEv3/azure-resource-manager/'
          branch_mode: create
          branch: 'arm-${{github.run_number}}'
          add: 'ase-arm.json' 
